# Generated by Django 5.1.4 on 2026-02-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsAsked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('topic', models.CharField(max_length=200)),
                ('ai_answer', models.TextField()),
            ],
        ),
    ]
