# Generated by Django 5.1.4 on 2025-01-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_flashsale_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsale',
            name='discount_perc',
            field=models.SmallIntegerField(),
        ),
    ]
