# Generated by Django 5.1.4 on 2026-03-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_book_cover_book_pdf_alter_flashsale_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
